### ISSUE TITLE
[bug] error when new project folder already exists

### ISSUE THREAD

**Issue by IllustrisJack** [Imposter/vscode-lua-vu#35] opened 2022-06-02 00:17 UTC
This error appears when creating a new project using vua when the project folder defined already exists even when empty.

```
Failed to execute action
ENOENT: no such file or directory, lstat
'C:\Users\*UserName*\AppData\Local\Programs\Microsoft VS Code\.git'

Error: ENOENT: no such file or directory, lstat
'C:\Users\*UserName*\AppData\Local\Programs\Microsoft VS Code\.git'
```

**Comment by Imposter** [comment] 2022-07-23 14:38
@IllustrisJack I have not been able to reproduce this. I created an empty directory for the project before specifying that same path in Vua, and it creates the project successfully.

**Comment by IllustrisJack** [comment] 2022-07-23 14:41
works on C:/ doesn´t work on any other drive for me

**Comment by IllustrisJack** [comment] 2022-07-23 14:43
- directory: Z:\testproject
- file in folder: yxxyvyvx.rtf

error:
![grafik](https://user-images.githubusercontent.com/76592751/180609945-4854a9bc-fe0b-4068-b6d4-e507cf4ec79a.png)

**Comment by Imposter** [comment] 2022-07-23 14:45
I see, thanks for the repro. I'll look into it

**Comment by IllustrisJack** [comment] 2022-07-23 14:45
actually i might have written down the issue wrong back then

**Comment by IllustrisJack** [comment] 2022-07-23 14:46
problem only happens if a file already exists in the folder

**Comment by Imposter** [comment] 2022-07-23 14:46
No worries. I was able to repro it now. I think I know what the issue is so I'll have a fix out soon.

**Comment by Imposter** [comment] 2022-07-23 18:45
Fixed in https://github.com/Imposter/vscode-lua-vu/commit/5d00f3ef8d1e06db5c780495122807b7863a74a3

**Closed by Imposter** 2022-07-23 18:45 UTC
Labels: bug
